on:
  push:
    branches:
      - master
name: Deploy master branch to production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Setup aws
        uses: chrislennon/action-aws-cli@v1.1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Restore Serverless State
        run: aws s3 sync s3://codear-nextjs-serverless-deployment-state/juryou-web/production .serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: yarn deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          API_URL: ${{ secrets.API_URL }}
          IDP_URL: ${{ secrets.IDP_URL }}
      - name: Save Serverless State
        run: aws s3 sync .serverless s3://codear-nextjs-serverless-deployment-state/juryou-web/production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
